services:
  - type: web
    name: jadwal-kuliah-umg
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader; php artisan optimize
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:sYqUOOrhEUV75ciEfHkKK/YtZ9QZzc98D5CDED4uBS4=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: postgresql
          name: db-jadwal
          property: host
      - key: DB_PORT
        fromService:
          type: postgresql
          name: db-jadwal
          property: port
      - key: DB_DATABASE
        fromService:
          type: postgresql
          name: db-jadwal
          property: database
      - key: DB_USERNAME
        fromService:
          type: postgresql
          name: db-jadwal
          property: user
      - key: DB_PASSWORD
        fromService:
          type: postgresql
          name: db-jadwal
          property: password
      - key: SESSION_DRIVER
        value: cookie
      - key: APP_URL
        value: https://jadwal-kuliah-umg.onrender.com

databases:
  - name: db-jadwal
    type: postgresql
    version: "15"
